version: '3.9'
services:
  hyperagi-inference-chat:
    image: hyperagi/hyperagi-inference:last
    container_name: hyperagi-inference-chat-container
    ports:
      - "5200:5000"
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - WALLET_ADDRESS=${WALLET_ADDRESS}
      - SCRIPT_NAME=inference_chat.py
      - MODEL_NAME=HyperdustProtocol/ImHyperAGI-cog-llama2-7b-5908v2
      - PORT=5200
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    restart: always 

  hyperagi-inference-instruction:
    image: hyperagi/hyperagi-inference:last
    container_name: hyperagi-inference-instruction-container
    ports:
      - "5100:5000"
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - WALLET_ADDRESS=${WALLET_ADDRESS}
      - SCRIPT_NAME=inference_instruction.py
      - MODEL_NAME=HyperdustProtocol/HyperAuto-cog-llama2-7b-3792
      - PORT=5100
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    restart: always 
