version: '3.9'
services:
  hyperagi-inference-chat:
    image: hyperagi/hyperagi-inference-chat:last
    ports:
      - '5200:5000'
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - WALLET_ADDRESS=${WALLET_ADDRESS}
      - MODEL_NAME=HyperdustProtocol/ImHyperAGI-cog-llama3.1-8b-4839
      - PORT=5200
    runtime: nvidia
  hyperagi-inference-instruction:
    image: hyperagi/hyperagi-inference:last
    ports:
      - '5100:5000'
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - WALLET_ADDRESS=${WALLET_ADDRESS}
      - MODEL_NAME=HyperdustProtocol/HyperAuto-cog-llama3-8b-3407
      - PORT=5100
    runtime: nvidia
